config/routes.rb
Rails.application.routes.draw do

  resources :shoppinglistitems

  post "/shopping_list_quantities" => 'shoppinglistitems#update_quantities'

  root to: "products#index"
  # root to: ""

  resources :users

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  #product
  #create

  resources :products
  #
  # get "/products/new"  => "products#new"
  # get "/products"  => "products#create"
  # # get "/products/edit"  =>
  # #read
  # get "/products"  => "products#index"
  # get "/products/:id"  =>"products#show"
  # # update
  # get "/products/id/edit"  => "products#edit"
  # # , as: 'product'
  # patch "/products/id"  => "products#update"
  # #delete
  # delete "/products/:id"  => "products#destroy"


  resources :categories
  # #category
  #   #create
  #   get "/categories/new"  => "categories#new"
  #   post "/categories" => "categories#create"
  #   #read
  #   get "/categories" => "categories#index"
  #   get "/categories/:id"  => "categories#show"
  #   #update
  #   get "/categories/:id/edit" => "categories#edit"
  #   # , as: 'categories'
  #   #post
  #   patch "/categories/:id" => "categories#update"

    # get "/categories/update"

#     #delete
#     delete "/categories/:id" => "categories#destroy"
#     ######################################
#     #shoppinglist


  # resources :shoppinglists
  #   shoppinglists GET    /shoppinglists(.:format)          shoppinglists#index
  #                   POST   /shoppinglists(.:format)          shoppinglists#create
  #  new_shoppinglist GET    /shoppinglists/new(.:format)      shoppinglists#new
  # edit_shoppinglist GET    /shoppinglists/:id/edit(.:format) shoppinglists#edit
  #      shoppinglist GET    /shoppinglists/:id(.:format)      shoppinglists#show
  #                   PATCH  /shoppinglists/:id(.:format)      shoppinglists#update
  #                   PUT    /shoppinglists/:id(.:format)      shoppinglists#update
  #                   DELETE /shoppinglists/:id(.:format)      shoppinglists#destroy

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/shopping_list_item.rb
# == Schema Information
#
# Table name: shopping_list_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  quantity   :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingListItem < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/shoppinglistitems_controller.rb
class ShoppinglistitemsController < ApplicationController

  before_action :check_if_logged_in


  def update_quantities

    # raise 'hell'
    params[:item].each do |key, val|

      # puts "="*50
      # puts "id: #{key}, new qty: #{val}"

      s = ShoppingListItem.where(user: @current_user, product_id: key)
      s.update quantity: val

      # p s
      # puts s.product_id, s.quantity
    end

    redirect_to shoppinglistitems_path
  end

  def new
    # @product = Product.new
    @categories = Category.all
    @users = User.all
    @shoppinglistitems = ShoppingListItem.all
  end

  def create
    # # @shoppinglistitem = ShoppingListItem.new shoppinglistitem_params
    # @shoppinglistitem = Product.new product_params
    # # need to find  what product id  and decrease the number of them
    #
    # raise 'hell'
    s = ShoppingListItem.find_by(product_id: params[:product_id], user: @current_user )
    if s.present?
      # raise 'hell'
       s.update quantity: params[:quantity].to_i + s.quantity
      # update_quantities
    else
      ShoppingListItem.create product_id: params[:product_id], quantity: params[:quantity], user:
    @current_user
    end
    redirect_to shoppinglistitems_path
  end

  def edit
    @shoppinglistitem = ShoppingListItem.find params["id"]
    @product = Product.new
    @categories = Category.all
    @users = User.all
  end

  def update
    @shoppinglistitem = ShoppingListItem.find params["id"]
    @shoppinglistitem.update shoppinglistitem_params
    s = ShoppingListItem.find_by(product_id: params[:product_id], user: @current_user )
    if s.present?
      # raise 'hell'
      s.update quantity: params[:quantity].to_i + s.quantity
    else
      ShoppingListItem.create product_id: params[:product_id], quantity: params[:quantity], user:
    @current_user
    end
    redirect_to shoppinglistitems_path

    redirect_to "shoppinglistitem_path"
  end
  def index
    @shoppinglistitems = ShoppingListItem.where user: @current_user
    # puts "&"*50, @shoppinglistitems.pluck(:product_id)

  end

  def show
    @shoppinglistitem = ShoppingListItem.find params["id"]
  end

  def destroy

    ShoppingListItem.find(params["id"]).destroy
    redirect_to shoppinglistitems_path
  end

  private
  def shoppinglistitem_params
    params.require( :shoppinglistitem).permit(:product_id, :quantity, :user_id)
  end

end

app/helpers/shoppinglistitems_helper.rb
module ShoppinglistitemsHelper
end

app/views/shoppinglistitems/create.html.erb
<h1>Shoppinglistitems#create</h1>
<p>Find me in app/views/shoppinglistitems/create.html.erb</p>

app/views/shoppinglistitems/destroy.html.erb
<h1>Shoppinglistitems#destroy</h1>
<p>Find me in app/views/shoppinglistitems/destroy.html.erb</p>

app/views/shoppinglistitems/edit.html.erb
<h2>Edit Shoppinglistitems</h2>
<!-- editing shoppinglistitems  loop through the products and show the user name -->
<%= form_for @shoppinglistitem do |s| %>
  <p>
    List of Users
    <%= s.label :user_id %>
    <%= s.collection_select( :user_ids,@users, :id, :name, include_blank: true) %>
  </p>
  <br>
  <p>
    <!-- list sll the products -->
    List of Products
    <%= s.label :product_id %>
    <%= s.collection_select( :product_ids,@products, :id, :name, include_blank: true) %>
  </p>
  <br>
  <p>
    Quantity
  </p>

  <br>
  <%= s.submit class:"btn btn-success" %>
  <% end %>

app/views/shoppinglistitems/index.html.erb
<h2>shoppinglistitems Index</h2>
<!-- list all the shopping list items and the quantities for each product  -->

<%= form_tag shopping_list_quantities_path do %>
<!-- loop through the shoppinglistitemsto get the quntites for each product -->
<ul>
  <div class="form-group">
  <% @total = 0 %>
  <% @shoppinglistitems.each do |s| %>
  <li>
    <%= link_to s.product.name, product_path(s.product) %>
    <%= text_field_tag "item[#{s.product.id}]", s.quantity , size: 4 %>
    <!-- , input_html: { min: 0 } -->
    <%= link_to 'Delete', shoppinglistitem_path(s), method: :delete %>
    <%= link_to 'Back', :back %>
    <!-- calculate the total price for each product by multipling with the quantity -->
    <% @total += (s.product.price * s.quantity) %>
  </li>
  <% end %>
  </div>
</ul>
<!-- add button to update  the products in the shoppinglistitems -->
<%= submit_tag 'Update the product list', class:" btn btn-succesbtn btn-success"%>
<% end %>
<br>
<%= button_to 'Add another product', products_path, method: :get, class:"btn btn-success btn btn-success" %>


<%# @shoppinglistitems.each do |s| %>
<%#= s.product.price %>

<%# end %>
<br>
<!-- print the total for each user in his ShoppingListItem -->
<p>Total Price: <%= number_to_currency @total %></p>

app/views/shoppinglistitems/new.html.erb
<h2>Create New Shoppinglistitem</h2>
<%= form_for @shoppinglistitem do |s| %>

<p>
  List of Users
  <%= s.label :user_id %>
  <%= s.collection_select( :user_ids,@users, :id, :name, include_blank: true) %>
</p>
<br>
<p>
  List of Products
  <%= s.label :product_id %>
  <%= s.collection_select( :product_ids,@products, :id, :name, include_blank: true) %>
</p>
<br>
<!--help with quantity  -->
<p>
  Quantity

</p>

<%= s.submit %>
<% end %>

app/views/shoppinglistitems/show.html.erb
<h2>Shoppinglistitem Details</h2>
<p>
  User: <%= @user.name %>
</p>
<br>
<p>List of Products
  <% @products each do |p| %>
    <a href="/products/<%= p.id %>"><%= p.name %></a>
  <% end %>
</p>
<br>
<p>
  <!-- Lukey, can ou check how to link her shopping list and remove correctly. A little messed up with the premise of what a shopping list is.  It should just be a many to many from users - products right?  Then jsut a bit lost of the steps of making the association and then deleting the associaiton.  -->
  <a data-method="delete" href="/products/<%= product.id %>">Delete</a>
  <%= @shoppinglistitem.products.each do |s| %>
    <%= link_to "remove product", product, :method => :delete, :confirm => "Are you sure?",:remote => true %>
<% end %>
<p>
  Number of products inside store:
<% @products each do |p| %>
  <% if product.number =< 0 %>
    errors.add(:product, :product.name, "is not available in store.")
  <% end %>
<% end %>
</p>
<p>
  <% @products each do |p| %>
    Quantity: <%= @products.length %>
    Number of product inside store currently is : <%= p.number %>
    Total price: <%= @products.length %> * p.price
  <% end %>
</p>


<% if @current_user %>
  <h2>Hello, <%= @current_user.name %></h2>
<% else %>
  <h2>Hello, guest</h2>
  <h3>Search product: </h3>
  <%= form_tag shoppinglistitems_path, method: :get do %>
    <div>
      <%= text_field_tag :search, params[:search],
      placeholder: 'Search product', type: :search, style: 'width: 400px' %>
    </div>
    <div><%= submit_tag 'Search' %></div>
  <% end %>

app/views/shoppinglistitems/update.html.erb
<h1>Shoppinglistitems#update</h1>
<p>Find me in app/views/shoppinglistitems/update.html.erb</p>