config/routes.rb
Rails.application.routes.draw do

  resources :shoppinglistitems

  post "/shopping_list_quantities" => 'shoppinglistitems#update_quantities'

  root to: "products#index"
  # root to: ""

  resources :users

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  #product
  #create

  resources :products
  #
  # get "/products/new"  => "products#new"
  # get "/products"  => "products#create"
  # # get "/products/edit"  =>
  # #read
  # get "/products"  => "products#index"
  # get "/products/:id"  =>"products#show"
  # # update
  # get "/products/id/edit"  => "products#edit"
  # # , as: 'product'
  # patch "/products/id"  => "products#update"
  # #delete
  # delete "/products/:id"  => "products#destroy"


  resources :categories
  # #category
  #   #create
  #   get "/categories/new"  => "categories#new"
  #   post "/categories" => "categories#create"
  #   #read
  #   get "/categories" => "categories#index"
  #   get "/categories/:id"  => "categories#show"
  #   #update
  #   get "/categories/:id/edit" => "categories#edit"
  #   # , as: 'categories'
  #   #post
  #   patch "/categories/:id" => "categories#update"

    # get "/categories/update"

#     #delete
#     delete "/categories/:id" => "categories#destroy"
#     ######################################
#     #shoppinglist


  # resources :shoppinglists
  #   shoppinglists GET    /shoppinglists(.:format)          shoppinglists#index
  #                   POST   /shoppinglists(.:format)          shoppinglists#create
  #  new_shoppinglist GET    /shoppinglists/new(.:format)      shoppinglists#new
  # edit_shoppinglist GET    /shoppinglists/:id/edit(.:format) shoppinglists#edit
  #      shoppinglist GET    /shoppinglists/:id(.:format)      shoppinglists#show
  #                   PATCH  /shoppinglists/:id(.:format)      shoppinglists#update
  #                   PUT    /shoppinglists/:id(.:format)      shoppinglists#update
  #                   DELETE /shoppinglists/:id(.:format)      shoppinglists#destroy

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  shoppingList_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#

class User < ApplicationRecord
  has_secure_password
  has_many :shopping_list_items
  validates :email, presence: true, uniqueness: true, length: {minimum: 5}
  validates :name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:show, :edit, :update]
  # [:show, :edit,:update]
  before_action :check_if_admin, only: [:edit, :update, :index]
  before_action :check_if_logged_in

  def get_user
    @user = User.find params["id"]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.id.present?
      session[:user_id] = @user.id  # perform login (set session)
      redirect_to user_path(@user.id)   # /users/17
    else
      render :new
    end

  end

  def index
    @users = User.all
  end
  def edit
    redirect_to root_path unless @current_user == @user || @current_user.admin?
  end

  def update
    @user = @current_user unless @current_user.admin?  # admin can edit anyone
    @user.update user_params
  redirect_to user_path( params["id"] )
  end

  def show
    redirect_to products_path unless @user == @current_user || @current_user.admin?
  end


  def destroy
  end
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end


end

# class UsersController < ApplicationController
#   def new
#   end
#
#   def create
#   end
#
#   def edit
#   end
#
#   def update
#   end
#
#   def index
#   end
#
#   def show
#   end
#
#   def destroy
#   end
# end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form>
<%= form_for @user  do |f| %>

  <%= f.label :email, class:"col-sm-2 control-label" %>
  <%= f.email_field :email ,class:"form-control"%>
  <br>
  <%= f.label :password, class:"col-sm-2 control-label" %>
  <%= f.password_field :password, class:"col-sm-2 control-label"%>
  <br>
  <%= f.label :password_confirmation ,class:"col-sm-2 control-label"%>
  <%= f.password_field :password_confirmation ,class:"form-control", id:"inputPassword3" %>
  <br>
  <%= f.label :name, class:"col-sm-2 control-label"%>
  <%= f.text_field :name, class:"col-sm-2 control-label" %>
<br>
  <%= f.submit class:"btn btn-default" %>
<% end %>
<form>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit Account</h2>
<%= render partial: 'form' %>

app/views/users/index.html.erb
<h2>Users Index</h2>

<div class="form-group">
<table class="table table-bordered table table-hover">
<ol>
  <% @users.each do |u| %>
  <li>
    <%= link_to u.name, user_path(u.id) %>
  </li>
  <% end %>
</ol>

</table>

app/views/users/new.html.erb
<h2>Create Account</h2>
<% if @user.errors.any? %>
<ol>
  <% @user.erro.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ol>
<% end %>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<h2>User Details</h2>
<% if @current_user.admin? %>
  <%= link_to 'Edit profile', edit_user_path(@user) %>
<% end %>
<p>Email: <%= @user.email %></p>
<p>Name: <%= @user.name %></p>
<p>Shopping_List_Items:<%= @user.shoppingList_id %></p>

<ol>
  <% @user.shopping_list_items.each do |s| %>
  <li>
    <%= link_to s.product.name, product_path(s.product) %>
    <%= text_field_tag "item[#{s.product.id}]", s.quantity , size: 4 %>
    <!-- , input_html: { min: 0 } -->

    <%= link_to 'Delete', shoppinglistitem_path(s), method: :delete %>

    <%= link_to 'Back', :back %>

  </li>
  <% end %>

</ol>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>