config/routes.rb
Rails.application.routes.draw do

  resources :shoppinglistitems

  post "/shopping_list_quantities" => 'shoppinglistitems#update_quantities'

  root to: "products#index"
  # root to: ""

  resources :users

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  #product
  #create

  resources :products
  #
  # get "/products/new"  => "products#new"
  # get "/products"  => "products#create"
  # # get "/products/edit"  =>
  # #read
  # get "/products"  => "products#index"
  # get "/products/:id"  =>"products#show"
  # # update
  # get "/products/id/edit"  => "products#edit"
  # # , as: 'product'
  # patch "/products/id"  => "products#update"
  # #delete
  # delete "/products/:id"  => "products#destroy"


  resources :categories
  # #category
  #   #create
  #   get "/categories/new"  => "categories#new"
  #   post "/categories" => "categories#create"
  #   #read
  #   get "/categories" => "categories#index"
  #   get "/categories/:id"  => "categories#show"
  #   #update
  #   get "/categories/:id/edit" => "categories#edit"
  #   # , as: 'categories'
  #   #post
  #   patch "/categories/:id" => "categories#update"

    # get "/categories/update"

#     #delete
#     delete "/categories/:id" => "categories#destroy"
#     ######################################
#     #shoppinglist


  # resources :shoppinglists
  #   shoppinglists GET    /shoppinglists(.:format)          shoppinglists#index
  #                   POST   /shoppinglists(.:format)          shoppinglists#create
  #  new_shoppinglist GET    /shoppinglists/new(.:format)      shoppinglists#new
  # edit_shoppinglist GET    /shoppinglists/:id/edit(.:format) shoppinglists#edit
  #      shoppinglist GET    /shoppinglists/:id(.:format)      shoppinglists#show
  #                   PATCH  /shoppinglists/:id(.:format)      shoppinglists#update
  #                   PUT    /shoppinglists/:id(.:format)      shoppinglists#update
  #                   DELETE /shoppinglists/:id(.:format)      shoppinglists#destroy

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string
#  number     :integer
#  price      :float
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord
  has_many :shopping_list_items
  has_and_belongs_to_many :categories
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :check_if_admin
  # before_action :check_if_logged_in, :except => [:index,:show]

  def new
    @product = Product.new
    @categories = Category.all
    @users = User.all
    # @categories = Category.all
  end

  def create
    # product = Product.find params["id"]
    # product = Product.create({
    # name: params["name"],
    # number: params["number"],
    # price: params["price"],
    # image: params["image"]
    # })
    # raise

    # raise 'hell'

    @product = Product.new product_params
    if params[:file].present?
      #perform upload to cloudinaray
      req = Cloudinary::Uploader.upload params[:file]
      @product.image = req['public_id']
    end

    # cloudinaryid public var and ny one use thie url can use it replace every image with this code

    @product.save
    redirect_to product_path(@product)     # "/products/#{ @product.id }"

  end

  def edit
    @product = Product.find params["id"]
    @categories = Category.all
  end

  def update
      @product = Product.find params["id"]
      # Product.update product_params
      @product.update product_params
      # ({
      #   name: params["name"],
      #   number: params["number"],
      #   price: params["price"]
      # })
      if params[:file].present?
        #perform upload to cloudinaray
        req = Cloudinary::Uploader.upload params[:file]
        @product.image = req['public_id']
      end
      @product.save
      redirect_to "/products/#{ @product.id }"
  end

  def show
    @product = Product.find params["id"]
    # @user = User.find params["id"]
    # redirect_to "/users/#{ @user.id }"
  end

  def index
    @products = Product.all
  end

  def destroy
    Product.find( params["id"]).destroy
    redirect_to "/products"
  end

  private
  def product_params
    params.require(:product).permit(:name, :number, :price, :image, category_ids:[])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/create.html.erb
<h1>Products create</h1>
<!-- <p>Find me in app/views/products/create.html.erb</p> -->

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<!-- edit the product which category belongs to so we loop through the categories and adding bootstrap  -->
<h2 class="bg-info">Edit Product</h2>
<%= form_for @product, html: {multipart: true} do |p| %>
<p class="bg-info">List of Categories
  <%=p.label :category_id,class:"bg-info" %>

  <div>
    <%= p.label "categories",class:"bg-info"%><br>
    <%= p.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>

      <div>
        <%= c.check_box( class:"bg-info")%>
        <%= c.label(class:"bg-info") %>
      </div>
    <% end %>
  </div>

</p>
<br>
<p>
  <%= p.label :name,class:"bg-info"  %>
  <%= p.text_field :name, required: true,class:"bg-info" %>
</p>
<br>
<p>
  <%= p.label :number,class:"bg-info"  %>
  <%= p.text_field :number, required: true,class:"bg-info" %>
</p>
<br>
<p>
  <%= p.label :price,class:"bg-info"  %>
  <%= p.text_field :price, required: true,class:"bg-info" %>
</p>
<br>
<!-- Image URL: -->
<!-- <input type="text" name="image" value="<%= @product.image %>"> -->
<p>
  <%= p.label :image ,class:"bg-info" %>
  <%= p.cl_image_upload :image, class:"img-thumbnail",class:"bg-info"   %>
</p>

<br>
<%= p.submit class:"btn btn-success" %>
<% end %>

app/views/products/index.html.erb
<!-- the product index  -->
<h2> Products Index</h2>
<ol>
  <% @products.each do |product| %>
  <li>
    <a href="/products/<%= product.id %>"><%= product.name %></a>

  </li>
  <% end %>
</ol>
<!-- user the bootstrap search functionality -->
<div class="input-group">
  <%= form_tag(categories_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class: 'form-control' %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: 'btn btn-primary btn btn-default btn btn-success' %>
    </span>
  <% end %>
</div>
<br>
<%= link_to "Back", :back , class: "btn btn-default btn btn-default btn-lg active btn btn-success"%>

app/views/products/new.html.erb
<table class="table table-striped">

<h2>Create New Product</h2>
<%= form_for(@product, html: {multipart: true}) do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
</p>

<p>
  <%= f.label :number %>
  <%= f.text_field :number, required: true %>
</p>
<p>
  <%= f.label :category %>
  <%= f.collection_select( :category_ids, @categories, :id, :name, :multiple => true, :prompt => 'Select') %>
</p>

<p>
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
</p>

<p>
  <%= f.label :image %>
  <%= f.cl_image_upload :image, class: 'img-thumbnail' %>
</p>
<%= f.submit %>

<% end %>

</table>

app/views/products/show.html.erb
<h2>Product Details</h2>
<form>
<div class="form-group">
<p>Name: <%= @product.name %></p>
<p>Number:
<% if @product.number <= 0 %>
  <p>Out of stock</p>
  <% else %>
   <%= @product.number %></p>
<% end %>
</div>
<br>
<div class="form-group">
<p class="bg-primary">List of Categories:
  <% @product.categories.each do |c| %>
    <a href="/categories/<%= c.id %>"><%= c.name %></a>
<% end %>
</p>
</div>
<br>
<div class="form-group">
<p>Price: <%= @product.price %></p>
<br>
Image URL:
  <%= cl_image_tag(@product.image) %>

  <a href="/products/<%= @product.id %>/edit">Edit Product Details</a>
</div>
<hr>
<table class="table table-bordered table-hover">
<div class="form-group">
<%= form_tag shoppinglistitems_path do %>
  Quantity: <%= text_field_tag :quantity%>
  <%= submit_tag 'Add to Shopping List' %>
  <%= hidden_field_tag :product_id, @product.id %>
<% end %>
</div>

</table>
</form>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>