config/routes.rb
Rails.application.routes.draw do

  resources :shoppinglistitems

  post "/shopping_list_quantities" => 'shoppinglistitems#update_quantities'

  root to: "products#index"
  # root to: ""

  resources :users

  get    '/login' => 'session#new'
  post   '/login' => 'session#create'
  delete '/login' => 'session#destroy'


  #product
  #create

  resources :products
  #
  # get "/products/new"  => "products#new"
  # get "/products"  => "products#create"
  # # get "/products/edit"  =>
  # #read
  # get "/products"  => "products#index"
  # get "/products/:id"  =>"products#show"
  # # update
  # get "/products/id/edit"  => "products#edit"
  # # , as: 'product'
  # patch "/products/id"  => "products#update"
  # #delete
  # delete "/products/:id"  => "products#destroy"


  resources :categories
  # #category
  #   #create
  #   get "/categories/new"  => "categories#new"
  #   post "/categories" => "categories#create"
  #   #read
  #   get "/categories" => "categories#index"
  #   get "/categories/:id"  => "categories#show"
  #   #update
  #   get "/categories/:id/edit" => "categories#edit"
  #   # , as: 'categories'
  #   #post
  #   patch "/categories/:id" => "categories#update"

    # get "/categories/update"

#     #delete
#     delete "/categories/:id" => "categories#destroy"
#     ######################################
#     #shoppinglist


  # resources :shoppinglists
  #   shoppinglists GET    /shoppinglists(.:format)          shoppinglists#index
  #                   POST   /shoppinglists(.:format)          shoppinglists#create
  #  new_shoppinglist GET    /shoppinglists/new(.:format)      shoppinglists#new
  # edit_shoppinglist GET    /shoppinglists/:id/edit(.:format) shoppinglists#edit
  #      shoppinglist GET    /shoppinglists/:id(.:format)      shoppinglists#show
  #                   PATCH  /shoppinglists/:id(.:format)      shoppinglists#update
  #                   PUT    /shoppinglists/:id(.:format)      shoppinglists#update
  #                   DELETE /shoppinglists/:id(.:format)      shoppinglists#destroy

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlineshopping</title>
    <%= csrf_meta_tags %>
    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container-fluid">

    <nav>
      <% unless @current_user.present? %>
      <%= link_to 'Login', login_path ,class:"btn btn-primary bg-info"  %> | <%= link_to 'Signup', new_user_path,class:"bg-info btn btn-primary bg-info"  %>
      <% else %>
        <%# User IS logged in %>
        <strong><u><em>Welcome, <mark><%= link_to @current_user.name,   user_path( @current_user,class:"btn btn-primary bg-info"  ) %> </mark>|
        <%= link_to 'Logout', login_path, method: :delete,class:"btn btn-primary bg-info"  %></em></u></strong>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>